import { ORDER_STATUS } from "./constants.js";


const NEXT_STEP = {
  [ORDER_STATUS.PLACED]: ORDER_STATUS.PROCESSING,
  [ORDER_STATUS.PROCESSING]: ORDER_STATUS.READY_TO_SHIP,
  [ORDER_STATUS.READY_TO_SHIP]: ORDER_STATUS.SHIPPED,
  [ORDER_STATUS.SHIPPED]: ORDER_STATUS.DELIVERED,
  [ORDER_STATUS.DELIVERED]: null,
  [ORDER_STATUS.CANCELLED]: null
};

export default function workflowNextStatus(currentStatus) {
  return NEXT_STEP[currentStatus] || null;
}
